import '@/app/globals.css'
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: 'Server Actions (formAction)',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>{children}
      <Toaster
          position="top-right"
          reverseOrder={false}
          toastOptions={{
            success: {
              style: {
                background: 'rgba(0, 255, 0, 0.1)',
              },
            },
            error: {
              style: {
                background: 'rgba(255, 0, 0, 0.1)',
              },
            },
          }} />
      </body>
      
    </html>
  )
}
